bump = "auto"
convention = "angular"
in-place = true
include-all = false
filter-commits = "fd44752.."
marker-line = "<!-- insertion marker -->"
output = "CHANGELOG.md"
parse-refs = true
parse-trailers = true
provider = "gitlab"
repository = "."
sections = ["docs", "fix", "feat", "perf","ci"]
template = "keepachangelog"
#version-regex = "^## \\\\[(?P<version>v?[^\\\\]]+)"
versioning = "semver"
zerover = true
